// Datos mock para la demo
export const mockMovies = [
  {
    _id: "1",
    tittle: "Inception",
    description: "Un ladrón que roba secretos corporativos a través del uso de tecnología de sueños compartidos.",
    genre: "Ciencia Ficción",
    releaseYear: 2010,
    director: "Christopher Nolan",
    averageRating: 4.8,
  },
  {
    _id: "2",
    tittle: "La La Land",
    description: "Una historia de amor entre un pianista de jazz y una aspirante a actriz en Los Ángeles.",
    genre: "Musical",
    releaseYear: 2016,
    director: "Damien Chazelle",
    averageRating: 4.5,
  },
  {
    _id: "3",
    tittle: "Parasite",
    description: "Una familia pobre se infiltra en la vida de una familia rica con consecuencias inesperadas.",
    genre: "Thriller",
    releaseYear: 2019,
    director: "Bong Joon-ho",
    averageRating: 4.7,
  },
  {
    _id: "4",
    tittle: "The Grand Budapest Hotel",
    description: "Las aventuras de un conserje legendario en un famoso hotel europeo.",
    genre: "Comedia",
    releaseYear: 2014,
    director: "Wes Anderson",
    averageRating: 4.3,
  },
  {
    _id: "5",
    tittle: "Mad Max: Fury Road",
    description: "En un mundo post-apocalíptico, Max se une a Furiosa para escapar de un tirano.",
    genre: "Acción",
    releaseYear: 2015,
    director: "George Miller",
    averageRating: 4.6,
  },
  {
    _id: "6",
    tittle: "Moonlight",
    description: "La historia de un joven afroamericano navegando su identidad y sexualidad.",
    genre: "Drama",
    releaseYear: 2016,
    director: "Barry Jenkins",
    averageRating: 4.4,
  },
]

export const mockMusic = [
  {
    _id: "1",
    name: "Bohemian Rhapsody",
    album: "A Night at the Opera",
    artist: "Queen",
    genre: "Rock",
    year: 1975,
    averageRating: 4.9,
  },
  {
    _id: "2",
    name: "Billie Jean",
    album: "Thriller",
    artist: "Michael Jackson",
    genre: "Pop",
    year: 1983,
    averageRating: 4.7,
  },
  {
    _id: "3",
    name: "Hotel California",
    album: "Hotel California",
    artist: "Eagles",
    genre: "Rock",
    year: 1976,
    averageRating: 4.8,
  },
  {
    _id: "4",
    name: "Imagine",
    album: "Imagine",
    artist: "John Lennon",
    genre: "Rock",
    year: 1971,
    averageRating: 4.6,
  },
  {
    _id: "5",
    name: "Smells Like Teen Spirit",
    album: "Nevermind",
    artist: "Nirvana",
    genre: "Grunge",
    year: 1991,
    averageRating: 4.5,
  },
  {
    _id: "6",
    name: "What's Going On",
    album: "What's Going On",
    artist: "Marvin Gaye",
    genre: "Soul",
    year: 1971,
    averageRating: 4.7,
  },
]

export const mockFood = [
  {
    _id: "1",
    name: "Sushi",
    description: "Arroz sazonado acompañado de pescado crudo, mariscos y vegetales.",
    countryOfOrigin: "Japón",
    ingredients: ["Arroz", "Pescado crudo", "Nori", "Wasabi", "Jengibre"],
    averageRating: 4.6,
  },
  {
    _id: "2",
    name: "Pizza Margherita",
    description: "Pizza tradicional italiana con tomate, mozzarella y albahaca fresca.",
    countryOfOrigin: "Italia",
    ingredients: ["Masa de pizza", "Tomate", "Mozzarella", "Albahaca", "Aceite de oliva"],
    averageRating: 4.4,
  },
  {
    _id: "3",
    name: "Tacos al Pastor",
    description: "Tacos mexicanos con carne de cerdo marinada y piña.",
    countryOfOrigin: "México",
    ingredients: ["Tortilla de maíz", "Carne de cerdo", "Piña", "Cebolla", "Cilantro"],
    averageRating: 4.7,
  },
  {
    _id: "4",
    name: "Pad Thai",
    description: "Fideos de arroz salteados con camarones, tofu y vegetales.",
    countryOfOrigin: "Tailandia",
    ingredients: ["Fideos de arroz", "Camarones", "Tofu", "Brotes de soja", "Cacahuates"],
    averageRating: 4.3,
  },
  {
    _id: "5",
    name: "Croissant",
    description: "Pastelería francesa hojaldrada en forma de media luna.",
    countryOfOrigin: "Francia",
    ingredients: ["Harina", "Mantequilla", "Levadura", "Leche", "Azúcar"],
    averageRating: 4.2,
  },
  {
    _id: "6",
    name: "Paella",
    description: "Plato tradicional español con arroz, mariscos y azafrán.",
    countryOfOrigin: "España",
    ingredients: ["Arroz", "Mariscos", "Azafrán", "Pimientos", "Judías verdes"],
    averageRating: 4.5,
  },
]

export const mockReviews = [
  {
    _id: "1",
    user: { username: "cinefilo123" },
    type: "Película",
    item: "1",
    rating: 5,
    comment: "Una obra maestra del cine. La complejidad de los sueños dentro de sueños es fascinante.",
    linkedMusic: mockMusic[2],
    linkedFood: mockFood[0],
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    _id: "2",
    user: { username: "musiclover" },
    type: "Música",
    item: "1",
    rating: 5,
    comment: "La mejor canción de rock de todos los tiempos. Freddie Mercury era un genio.",
    linkedMovie: mockMovies[1],
    linkedFood: mockFood[4],
    createdAt: "2024-01-14T15:45:00Z",
  },
  {
    _id: "3",
    user: { username: "foodie_expert" },
    type: "Comida",
    item: "1",
    rating: 5,
    comment: "El sushi auténtico es una experiencia única. La frescura del pescado es incomparable.",
    linkedMovie: mockMovies[0],
    linkedMusic: mockMusic[3],
    createdAt: "2024-01-13T20:15:00Z",
  },
  {
    _id: "4",
    user: { username: "reviewer_pro" },
    type: "Película",
    item: "2",
    rating: 4,
    comment: "Una hermosa historia de amor con música increíble. Ryan Gosling y Emma Stone brillan.",
    linkedMusic: mockMusic[1],
    linkedFood: mockFood[4],
    createdAt: "2024-01-12T14:20:00Z",
  },
]

export const mockUser = {
  id: "user1",
  username: "demo_user",
  email: "demo@example.com",
}

export const mockTopItems = {
  movies: [
    { itemDetails: mockMovies[0], averageRating: 4.8, reviewCount: 156 },
    { itemDetails: mockMovies[2], averageRating: 4.7, reviewCount: 143 },
    { itemDetails: mockMovies[4], averageRating: 4.6, reviewCount: 128 },
    { itemDetails: mockMovies[1], averageRating: 4.5, reviewCount: 134 },
    { itemDetails: mockMovies[5], averageRating: 4.4, reviewCount: 98 },
  ],
  music: [
    { itemDetails: mockMusic[0], averageRating: 4.9, reviewCount: 203 },
    { itemDetails: mockMusic[2], averageRating: 4.8, reviewCount: 187 },
    { itemDetails: mockMusic[1], averageRating: 4.7, reviewCount: 165 },
    { itemDetails: mockMusic[5], averageRating: 4.7, reviewCount: 142 },
    { itemDetails: mockMusic[3], averageRating: 4.6, reviewCount: 156 },
  ],
  food: [
    { itemDetails: mockFood[2], averageRating: 4.7, reviewCount: 189 },
    { itemDetails: mockFood[0], averageRating: 4.6, reviewCount: 167 },
    { itemDetails: mockFood[5], averageRating: 4.5, reviewCount: 145 },
    { itemDetails: mockFood[1], averageRating: 4.4, reviewCount: 178 },
    { itemDetails: mockFood[3], averageRating: 4.3, reviewCount: 134 },
  ],
}
